resources:
  jobs:
    predictive_maintenance_model_deployment:
      name: "Predictive Maintenance - Model Deployment"

      tasks:
        - task_key: "deploy_model"
          spark_python_task:
            python_file: "../src/lakehouse/models/deployment.py"
          job_cluster_key: "deployment_cluster"

      job_clusters:
        - job_cluster_key: "deployment_cluster"
          new_cluster:
            spark_version: "17.2.x-scala2.13"
            node_type_id: "Standard_DS3_v2"
            num_workers: 0
            spark_conf:
              "spark.databricks.cluster.profile": "singleNode"
              "spark.master": "local[*]"
            custom_tags:
              "ResourceClass": "SingleNode"
